language: go

notifications:
  email: false

sudo: required
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install libegl1-mesa-dev libgles2-mesa-dev
  travis_retry curl -L https://www.libsdl.org/release/SDL2-2.0.8.tar.gz | tar xz
  cd SDL2-2.0.8
  ./configure
  make
  sudo make install
  - sudo apt-get install libsdl2-image-dev libsdl2-ttf-dev xclip